version: '3'

services:
  database:
    build:
      context: ./server
      dockerfile: Dockerfile-db
    ports:
      - 5432:5432
    healthcheck:
      test: "exit 0"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile-back
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy